export type PortalMonthlyMonitoringReport = {
  id: string
  month: number
  year: number
  declaredAt: Date | string | null
  columns: Array<{ id: string; label: string; type: 'COURSE' | 'CUSTOM' }>
  student: {
    name: string
    rollNumber: string
    courseMarks: Record<string, { totalMarks: number; obtainedMarks: number }>
    customValues: Record<string, string>
    remarks: string
    totalMarks: number
    obtainedMarks: number
    percentage: number
    performanceBatch: string
    rank: number
  }
}

export type StoredMonthlyMonitoringReport = {
  id: string
  classSectionId: string
  month: number
  year: number
  academicYearId: string
  declarationStatus: 'DRAFT' | 'DECLARED'
  declaredAt: Date | null
  reportData: unknown
}

/**
 * Temporary boundary for new schema fields while local Prisma artifacts are
 * regenerated by the deployment's postinstall step. It keeps the application
 * code typed without requiring generated files in source control.
 */
export type MonthlyMonitoringRepository = {
  findUnique(args: unknown): Promise<StoredMonthlyMonitoringReport | null>
  findMany(args: unknown): Promise<StoredMonthlyMonitoringReport[]>
  upsert(args: unknown): Promise<StoredMonthlyMonitoringReport>
  update(args: unknown): Promise<StoredMonthlyMonitoringReport>
  updateMany(args: unknown): Promise<{ count: number }>
}

type PortalMonitoringReportSource = Pick<
  StoredMonthlyMonitoringReport,
  'id' | 'month' | 'year' | 'declaredAt' | 'reportData'
>

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function asFiniteNumber(value: unknown): number {
  const numberValue = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(numberValue) ? numberValue : 0
}

/**
 * Removes classmates' data from a stored monthly report before it reaches a
 * student or guardian portal. Snapshots are class-scoped in the database, but
 * portal responses must always be student-scoped.
 */
export function toPortalMonthlyMonitoringReport(
  report: PortalMonitoringReportSource,
  studentId: string,
): PortalMonthlyMonitoringReport | null {
  if (!isRecord(report.reportData)) return null

  const rawColumns = Array.isArray(report.reportData.columns) ? report.reportData.columns : []
  const columns = rawColumns.flatMap((column) => {
    if (!isRecord(column) || typeof column.id !== 'string' || typeof column.label !== 'string') return []
    return [{
      id: column.id,
      label: column.label,
      type: column.type === 'COURSE' ? 'COURSE' as const : 'CUSTOM' as const,
    }]
  })

  const rawStudents = Array.isArray(report.reportData.students) ? report.reportData.students : []
  const source = rawStudents.find((row) => isRecord(row) && row.studentId === studentId)
  if (!isRecord(source)) return null

  const courseMarks = Object.fromEntries(
    Object.entries(isRecord(source.courseMarks) ? source.courseMarks : {}).flatMap(([columnId, value]) => {
      if (!isRecord(value)) return []
      return [[columnId, {
        totalMarks: asFiniteNumber(value.totalMarks),
        obtainedMarks: asFiniteNumber(value.obtainedMarks),
      }]]
    }),
  )
  const customValues = Object.fromEntries(
    Object.entries(isRecord(source.customValues) ? source.customValues : {}).flatMap(([columnId, value]) =>
      typeof value === 'string' ? [[columnId, value]] : [],
    ),
  )

  return {
    id: report.id,
    month: report.month,
    year: report.year,
    declaredAt: report.declaredAt,
    columns,
    student: {
      name: typeof source.name === 'string' ? source.name : '',
      rollNumber: typeof source.rollNumber === 'string' ? source.rollNumber : '',
      courseMarks,
      customValues,
      remarks: typeof source.remarks === 'string' ? source.remarks : '',
      totalMarks: asFiniteNumber(source.totalMarks),
      obtainedMarks: asFiniteNumber(source.obtainedMarks),
      percentage: asFiniteNumber(source.percentage),
      performanceBatch: typeof source.performanceBatch === 'string' ? source.performanceBatch : 'Improvement Group',
      rank: asFiniteNumber(source.rank),
    },
  }
}
