#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Evershine Academy LMS — Production Startup Script
# ═══════════════════════════════════════════════════════════════════════════════
#
# Hostinger Node.js apps do NOT deploy the .env file (it is gitignored).
# Environment variables must be set via hPanel → Node.js Web App → Environment.
# This script validates critical vars are present before starting Next.js.
#
# Usage:
#   PRODUCTION=1 bash scripts/prod-start.sh
#
# Or in package.json:
#   "start": "bash scripts/prod-start.sh"
# ═══════════════════════════════════════════════════════════════════════════════

set -e

echo "=== Evershine Academy LMS — Production Startup ==="

# ── 1. Validate critical environment variables ──────────────────────────────

missing=0
check_var() {
  local var_name="$1"
  local hint="$2"
  if [ -z "${!var_name}" ]; then
    echo "[MISSING] $var_name — $hint"
    missing=1
  else
    echo "[OK]     $var_name"
  fi
}

check_var "DATABASE_URL" "Set in hPanel → Node.js → Environment. Must start with mysql://"
check_var "NEXTAUTH_SECRET" "Generate with: openssl rand -hex 32"
check_var "NEXTAUTH_URL" "Set to your production URL, e.g. https://lms.evershineacademy.edu.pk"

if [ "$missing" -eq 1 ]; then
  echo ""
  echo "ERROR: One or more critical environment variables are missing."
  echo "Set them in Hostinger hPanel → Node.js Web App → Environment Variables."
  echo ""
  echo "Required:"
  echo "  DATABASE_URL=\"mysql://user:pass@localhost:3306/dbname\""
  echo "  NEXTAUTH_SECRET=\"<openssl rand -hex 32>\""
  echo "  NEXTAUTH_URL=\"https://yourdomain.com\""
  echo "  NODE_ENV=\"production\""
  exit 1
fi

# Validate DATABASE_URL format
if echo "$DATABASE_URL" | grep -qv "^mysql://"; then
  echo ""
  echo "ERROR: DATABASE_URL must start with mysql://"
  echo "  Current value: ${DATABASE_URL:0:30}..."
  echo "  Expected: mysql://user:pass@host:3306/dbname"
  echo "  Fix in hPanel → Node.js → Environment Variables."
  exit 1
fi

# ── 2. If .env does not exist (gitignored), create it from env vars ────────
# This ensures libraries that read .env directly (like Prisma in some configs)
# still find their settings.
if [ ! -f .env ]; then
  echo "[SETUP] Creating .env from production environment variables..."
  {
    echo "# Auto-generated by prod-start.sh — $(date -u)"
    echo "# Do not commit. Contents sourced from hPanel environment variables."
    echo ""
    echo "DATABASE_URL=\"$DATABASE_URL\""
    echo "NEXTAUTH_SECRET=\"$NEXTAUTH_SECRET\""
    echo "NEXTAUTH_URL=\"$NEXTAUTH_URL\""
    echo "NODE_ENV=\"production\""
    echo "NEXT_PUBLIC_APP_URL=\"$NEXT_PUBLIC_APP_URL\""
    echo "NEXT_PUBLIC_APP_NAME=\"$NEXT_PUBLIC_APP_NAME\""
    echo "NEXT_PUBLIC_ACADEMIC_ENGINE_PRIMARY=\"${NEXT_PUBLIC_ACADEMIC_ENGINE_PRIMARY:-true}\""
    echo ""
    echo "# Email (SMTP)"
    echo "SMTP_HOST=\"$SMTP_HOST\""
    echo "SMTP_PORT=\"${SMTP_PORT:-465}\""
    echo "SMTP_SECURE=\"${SMTP_SECURE:-true}\""
    echo "SMTP_USER=\"$SMTP_USER\""
    echo "SMTP_PASS=\"$SMTP_PASS\""
    echo "SMTP_FROM=\"$SMTP_FROM\""
  } > .env
fi

# ── 3. Start Next.js production server ─────────────────────────────────────
echo "[START] Starting Next.js production server on port ${PORT:-3000}..."
exec node node_modules/.bin/next start -p "${PORT:-3000}"
