#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Evershine Academy LMS — Production Startup Script
# ═══════════════════════════════════════════════════════════════════════════════
#
# Hostinger Node.js apps do NOT deploy the .env file (it is gitignored).
# Environment variables must be set via hPanel → Node.js Web App → Environment.
# This script validates critical vars are present before starting Next.js.
#
# Usage:
#   PRODUCTION=1 bash scripts/prod-start.sh
#
# Or in package.json:
#   "start": "bash scripts/prod-start.sh"
# ═══════════════════════════════════════════════════════════════════════════════

set -e

echo "=== Evershine Academy LMS — Production Startup ==="

# ── 1. Load local .env when present ─────────────────────────────────────────
# Hostinger hPanel variables remain the primary production source. Loading an
# existing .env keeps SSH/manual starts and local production smoke tests from
# failing before Node has a chance to read the same file.
if [ -f .env ]; then
  echo "[SETUP] Loading environment variables from existing .env"
  set -a
  . ./.env
  set +a
fi

# ── 2. Validate critical environment variables ──────────────────────────────

missing=0
check_var() {
  local var_name="$1"
  local hint="$2"
  if [ -z "${!var_name}" ]; then
    echo "[MISSING] $var_name — $hint"
    missing=1
  else
    echo "[OK]     $var_name"
  fi
}

check_var "DATABASE_URL" "Set in hPanel → Node.js → Environment. Must start with mysql://"
check_var "NEXTAUTH_SECRET" "Generate with: openssl rand -hex 32"
check_var "NEXTAUTH_URL" "Set to your production URL, e.g. https://lms.evershineacademy.edu.pk"

if [ "$missing" -eq 1 ]; then
  echo ""
  echo "ERROR: One or more critical environment variables are missing."
  echo "Set them in Hostinger hPanel → Node.js Web App → Environment Variables."
  echo ""
  echo "Required:"
  echo "  DATABASE_URL=\"mysql://user:pass@localhost:3306/dbname\""
  echo "  NEXTAUTH_SECRET=\"<openssl rand -hex 32>\""
  echo "  NEXTAUTH_URL=\"https://yourdomain.com\""
  echo "  NODE_ENV=\"production\""
  exit 1
fi

# Validate DATABASE_URL format
if echo "$DATABASE_URL" | grep -qv "^mysql://"; then
  echo ""
  echo "ERROR: DATABASE_URL must start with mysql://"
  echo "  Current value: ${DATABASE_URL:0:30}..."
  echo "  Expected: mysql://user:pass@host:3306/dbname"
  echo "  Fix in hPanel → Node.js → Environment Variables."
  exit 1
fi

# ── 3. If .env does not exist (gitignored), create it from env vars ────────
# This ensures libraries that read .env directly (like Prisma in some configs)
# still find their settings.
if [ ! -f .env ]; then
  echo "[SETUP] Creating .env from production environment variables..."
  {
    echo "# Auto-generated by prod-start.sh — $(date -u)"
    echo "# Do not commit. Contents sourced from hPanel environment variables."
    echo ""
    echo "DATABASE_URL=\"$DATABASE_URL\""
    echo "NEXTAUTH_SECRET=\"$NEXTAUTH_SECRET\""
    echo "NEXTAUTH_URL=\"$NEXTAUTH_URL\""
    echo "NODE_ENV=\"production\""
    echo "NEXT_PUBLIC_APP_URL=\"$NEXT_PUBLIC_APP_URL\""
    echo "NEXT_PUBLIC_APP_NAME=\"$NEXT_PUBLIC_APP_NAME\""
    echo "NEXT_PUBLIC_ACADEMIC_ENGINE_PRIMARY=\"${NEXT_PUBLIC_ACADEMIC_ENGINE_PRIMARY:-true}\""
    echo ""
    echo "# Email (SMTP)"
    echo "SMTP_HOST=\"$SMTP_HOST\""
    echo "SMTP_PORT=\"${SMTP_PORT:-465}\""
    echo "SMTP_SECURE=\"${SMTP_SECURE:-true}\""
    echo "SMTP_USER=\"$SMTP_USER\""
    echo "SMTP_PASS=\"$SMTP_PASS\""
    echo "SMTP_FROM=\"$SMTP_FROM\""
  } > .env
fi

# ── 4. Validate build artifacts before accepting traffic ───────────────────
if [ ! -f .next/BUILD_ID ]; then
  echo ""
  echo "ERROR: .next/BUILD_ID is missing. Run npm run build before starting production."
  echo "Hostinger must deploy a complete Next.js build, not source files alone."
  exit 1
fi

echo "[OK]     Next.js build ID: $(cat .next/BUILD_ID)"

if [ ! -d .next/static ]; then
  echo ""
  echo "ERROR: .next/static is missing. Static chunks will 404 in production."
  echo "Redeploy the complete build artifact and clear Hostinger/CDN cache."
  exit 1
fi

echo "[OK]     Next.js static assets present"

# ── 5. Ensure standalone distribution has required assets ──────────────────
# Next.js output: "standalone" bundles the server into .next/standalone but
# does NOT copy .next/static. Without this, every /_next/static/* request
# returns 404, causing "Failed to load chunk" browser errors.
STANDALONE_DIR=".next/standalone"
STANDALONE_STATIC="$STANDALONE_DIR/.next/static"

if [ -d "$STANDALONE_DIR" ]; then
  if [ ! -d "$STANDALONE_STATIC" ]; then
    echo "[SETUP] Copying .next/static → $STANDALONE_STATIC (standalone distribution)"
    mkdir -p "$STANDALONE_STATIC"
    cp -r .next/static/. "$STANDALONE_STATIC/"
  fi
  echo "[OK]     Standalone static assets ready"

  # public/ is already present inside standalone (copied by next build)
  START_CMD="node $STANDALONE_DIR/server.js"
else
  # Fallback: next start (used when build is not standalone)
  START_CMD="node node_modules/.bin/next start"
  echo "[WARN]   Standalone directory not found; falling back to next start"
fi

# ── 6. Start Next.js production server ─────────────────────────────────────
echo "[START] Starting Next.js production server on port ${PORT:-3000}..."
echo "[START] Command: $START_CMD -p ${PORT:-3000}"
exec $START_CMD -p "${PORT:-3000}"
